export const arrays = {
  ObjetoCotidiano : [
    "mesa", "silla", "teléfono", "lámpara", "televisor",
    "reloj", "computadora", "teclado", "ratón", "cargador",
    "libro", "bolígrafo", "cuaderno", "ventilador", "lentes",
    "taza", "plato", "cuchara", "tenedor", "cuchillo",
    "botella", "mochila", "zapatos", "camisa", "pantalones",
    "chaqueta", "sombrero", "cinturón", "llaves", "cartera",
    "peine", "espejo", "jabón", "toalla", "champú",
    "lavavajillas", "altavoz", "micrófono", "cámara", "impresora",
    "escáner", "coche", "auriculares", "disco duro", "tableta",
    "pendrive", "proyector", "colchón", "almohada", "manta",
    "cargador", "calculadora", "tijeras", "pegamento", "regla",
    "clip", "grapadora", "papelera", "marcador", "percha",
    "estante", "reproductor", "cerradura", "detergente", "esponja",
    "cubeta", "escoba", "recogedor", "aspiradora", "plancha",
    "horno", "microondas", "cafetera", "batidora", "olla",
    "sartén", "colador", "rallador", "abrelatas", "cortador",
    "tostadora", "nevera", "lavadora", "secadora", "ventana",
    "puerta", "alfombra", "cortina", "taburete",
    "fregadero", "grifos", "linterna",
    "paraguas", "cortauñas", "crema"
  ],
  
Comida : [
    "pizza", "hamburguesa", "sushi", "tacos", "espaguetis",
    "ensalada", "burrito", "sopa", "lasaña", "paella",
    "raviolis", "pollo", "ceviche", "guisantes", "empanadas",
    "falafel", "gnocchi", "quesadilla", "bocadillo", "ensaladilla",
    "kebab", "huevo frito", "tortilla", "filete", "gazpacho",
    "patatas", "canelones", "tarta", "creppes", "tequeños", "guisantes"
  ],
  
CiudadDelMundo : [
    "Nueva York", "Londres", "Tokio", "París", "Sídney",
    "Bagdag", "Roma", "Berlín", "Toronto", "Moscú", "Pekín",
    "Seúl", "Bangkok", "Dubái", "Johannesburgo", "Estambul",
    "Hong Kong", "Singapur", "Damasco", "Chicago", 
    "Lima", "Bogotá", "Johannesburgo", "Viena", "Ámsterdam",
    "Dublín", "Lisboa", "Praga", "Copenhague", "Atenas",
    "Estocolmo", "Bruselas", "Varsovia", "Helsinki", "Oslo",
    "Budapest", "Zúrich", "Ginebra", "Vancouver", "Montreal",
    "Melbourne", "Caracas",  "Atenas", "Rabat"
  ],

 CapitalDeProvincia : [
    "Almería", "Cádiz", "Córdoba", "Granada", "Huelva",
    "Jaén", "Málaga", "Sevilla", "Huesca", "Teruel",
    "Zaragoza", "Oviedo", "Palma", 
    "Santander", "Ávila", "Burgos", "León", "Palencia",
    "Salamanca", "Segovia", "Soria", "Valladolid", "Zamora",
    "Albacete",  "Cuenca", "Guadalajara", "Toledo",
    "Barcelona", "Girona", "Lleida", "Tarragona", "Alicante",
    "Castellón", "Valencia", "Badajoz", "Cáceres", "Coruña",
    "Lugo", "Ourense", "Pontevedra", "Madrid", "Murcia",
    "Pamplona", "Logroño", "Vitoria",  "Bilbao"
  ],
  
 Animal : [
    "perro", "gato", "caballo", "vaca", "cerdo",
    "oveja", "gallina", "pato", "ganso", "conejo",
    "hamster", "cobaya", "tortuga", "carpa", "canario",
    "loro", "periquito", "serpiente", "iguana", "camaleón",
    "elefante", "león", "tigre", "jirafa", "hipopótamo",
    "rinoceronte", "cebra", "canguro", "koala", "panda",
    "oso", "lobo", "zorro", "mono", "chimpancé",
    "gorila", "orangután", "delfín", "ballena", "tiburón",
    "pingüino", "foca", "león", "pelícano", "flamenco",
    "águila", "halcón", "búho", "cuervo", "paloma",
    "gorrión", "golondrina", "pato", "cisne", "grulla",
    "cigüeña", "medusa", "salmón", "cangrejo",
    "langosta", "buitre", "pulpo", "calamar", "mosca",
    "mosquito", "hormiga", "abeja", "avispa", "mariposa",
    "saltamontes", "grillo", "escarabajo", "caracol", "lombriz",
    "rana", "sapo", "cocodrilo", "caimán", "lagarto",
    "libélula", "jaguar", "cobra", "mapache", "avestruz",
    "jabalí", "pavo", "kiwi", "ratón", "rata",
    "ardilla", "castor", "marmota", "puercoespín", "erizo"
  ],
  
  País : [
    "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Argelia", "Argentina", "Armenia",
    "Australia", "Austria", "Azerbaiyán", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín",
    "Bielorrusia", "Birmania", "Bolivia", "Bosnia", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burundi",
    "Bután",  "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre",
    "Colombia", "Comoras", "Croacia", "Cuba", "Dinamarca", "Dominica",
    "Ecuador", "Egipto",  "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estonia",
    "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Grecia",
    "Guatemala", "Guinea","Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia",
    "Irak", "Irán", "Irlanda", "Islandia",  "Israel", "Italia", "Jamaica", "Japón",
    "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kosovo", "Kuwait", "Laos", "Lesoto", "Letonia",
    "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", "Malasia", "Malaui", "Maldivas",
    "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia",
    "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", 
    "Omán",  "Pakistán", "Palaos", "Panamá",  "Paraguay", "Perú", "Polonia", "Portugal",
    "Inglaterra","Ruanda", "Rumania", "Rusia", "Samoa",  "Senegal", "Serbia", "Singapur", "Siria",
    "Somalia",  "Suazilandia", "Sudáfrica", "Sudán",  "Suecia", "Suiza", "Surinam", "Tailandia",
    "Tanzania", "Tayikistán",  "Togo", "Tonga",  "Túnez", "Turkmenistán", "Turquía", "Tuvalu",
    "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Vaticano", "Venezuela", "Vietnam", "Yemen", "Yibuti",
    "Zambia", "Zimbabue"
]}
